# Generated by Django 5.2.4 on 2025-08-05 13:20

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_is_paid_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=orders.models.order_ID, max_length=30),
        ),
    ]
