# Generated by Django 5.2.4 on 2025-08-06 08:07

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=orders.models.order_ID, max_length=30, unique=True),
        ),
    ]
